# Generated by Django 4.2.6 on 2024-04-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newreg',
            old_name='fname',
            new_name='Gmail',
        ),
        migrations.RenameField(
            model_name='newreg',
            old_name='lname',
            new_name='name',
        ),
    ]
